provisioning_command: /bin/bash -c "/root/init.sh ; ralph demodata"
compose:
  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: ralph_ng
      MYSQL_ROOT_PASSWORD: ralph_ng
      MYSQL_USER: ralph_ng
      MYSQL_PASSWORD: ralph_ng
    volumes_from:
      - data

  web:
    build: .
    restart: always
    ports:
      - "8000"
    volumes_from:
      - data
    links:
      - db:db
      - redis:redis
    env_file:
      - ./contrib/ralph.env
    environment:
      - DJANGO_SETTINGS_MODULE=ralph.settings.prod
    command: gunicorn -w 4 -b 0.0.0.0:8000 -t 300 ralph.wsgi

  nginx:
    image: nginx
    restart: always
    ports:
      - "80"
    links:
      - web:web
    volumes:
      - ./contrib/ralph.conf.nginx:/etc/nginx/conf.d/default.conf
    volumes_from:
      - web

  data:
    image: mysql:5.6
    volumes:
      - /opt/static
      - /opt/media
      - /var/lib/mysql
    command: /bin/true

  redis:
    image: redis:3.0
    restart: always
    ports:
      - "6379"

  inkpy:
    image: ar4s/inkpy_jinja:latest
    restart: always
    links:
      - redis:redis
    env_file:
      - ./contrib/ralph.env

