language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install git+https://github.com/allegro/django-bob
  - make install
  - pip install flake8
  
  
# command to run tests, e.g. python setup.py test
script: make quicktest
before_script:
  make flake
  
