site_name: Ralph 3
repo_url: https://github.com/allegro/ralph/
pages:
  - Welcome: index.md
  - Installation guide:
      - Installation: installation/installation.md
      - Configuration: installation/configuration.md
      - 'Migration from Ralph 2.x': installation/data_migration.md
  - User guide:
      - Quickstart: user/quickstart.md
      - Advanced guide: user/guide.md
      - Domains management: user/domains.md
      - API: user/api.md
  - Developer guide:
      - Before you start: CONTRIBUTING.md
      - Architecture: development/overview.md
      - Transitions: development/transitions.md
      - Addons : development/addons.md
      - Packaging: development/packaging.md
      - FAQ: development/faq.md
theme: readthedocs
strict: true
dev_addr: 0.0.0.0:8000
markdown_extensions:
    - toc:
        permalink: True
site_dir: docs/_build/html  # sphinx compatible
